<h3 class="top">CO2 Meter</h3>
<div class="menu">
	<div>
		<a href="/index.htm">Main</a>
		<a href="/history.htm">History</a>
		<a href="/peak.htm">Peak chart</a>
	</div>
	<div>
		<a href="/protect/setmeter.htm">Setup meter</a>
		<a href="/settings.htm">Settings</a>
	</div>
</div>
<script type="text/javascript">
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>